### ISSUE TITLE
A college website landing page

### ISSUE THREAD

**Issue by Nitya-Pasrija** [GDSC-IGDTUW-Autumn-of-Code-2022/UX-UI-Case-Studies-and-Projects#40]
can you assign this to me? @SimPandit

**Comment by ASHWINISHARMABTCSAI118** [comment]
@SimPandit Can you please assign this to me.

**Comment by SHarshita0111** [comment]
@SimPandit Please kindly assign me with this project .

**Comment by SHarshita0111** [comment]
@SimPandit Please kindly assign me with this project .

**Comment by ShubhaSwarup** [comment]
can you please assign this to me

**Comment by singhapeksha** [comment]
Please Assign this to me.
