### ISSUE TITLE
A blogging website's dashboard

### ISSUE THREAD

**Issue by Nitya-Pasrija** [GDSC-IGDTUW-Autumn-of-Code-2022/UX-UI-Case-Studies-and-Projects#41]
I would love to work upon this one. Could you assign this to me? @SimPandit

**Comment by ASHWINISHARMABTCSAI118** [comment]
@SimPandit Can you please assign this to me.

**Comment by SHarshita0111** [comment]
@SimPandit Please kindly assign me with this project .

**Comment by ShubhaSwarup** [comment]
Can you please assign this to me

**Comment by singhapeksha** [comment]
Please Assign this to me.
