### ISSUE TITLE
Fashion Agency's landing page

### ISSUE THREAD

**Issue by Nitya-Pasrija** [GDSC-IGDTUW-Autumn-of-Code-2022/UX-UI-Case-Studies-and-Projects#60]
Can you assign this to me?

**Comment by SHarshita0111** [comment]
@SimPandit I would like to contribute in this project.

**Comment by ASHWINISHARMABTCSAI118** [comment]
@SimPandit  Can you assign me with this project!!

**Comment by singhapeksha** [comment]
Please Assign me this project
