### ISSUE TITLE
A website for plant selling

### ISSUE THREAD

**Issue by Nitya-Pasrija** [GDSC-IGDTUW-Autumn-of-Code-2022/UX-UI-Case-Studies-and-Projects#88]
Can you assign this to me?

**Comment by SHarshita0111** [comment]
@SimPandit kindly assign this project to me .

**Comment by ASHWINISHARMABTCSAI118** [comment]
@SimPandit can you assign this to me?

**Comment by trushee** [comment]
@SimPandit I would like to work on this issue. Kindly assign it to me. Thanks!
